# trigger:
# - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  subscription: 2688a180-ce56-47e0-98ae-04064c97f5c4
  resourceGroup: rg-eris-terraform-test
  storageAccount: terraformtfstateskip
  container: tfstate
  tfstateFile: terraform.tfstate
  anyTfChanges: false

steps:

- task: TerraformInstaller@0
  displayName: install Terraform v0.12.28
  inputs:
    terraformVersion: '0.12.28'

